name: default-environment
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - glue-jupyter>=0.26
  - plotly
  - scikit-image
  - anywidget
  - pip:
    - glue-plotly
    - ipyfilechooser
